services:
  fastapi:
    build: .
    ports:
      - 8000
    environment:
      - DB_HOST=${HOST}
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb